In [1]:
import numpy as np

import matplotlib.pyplot as pp

In [3]:
a=np.array([[1,2,3,4,5],[4,3,4,3,4],[2,2,5,6,2]])
a

array([[1, 2, 3, 4, 5],
       [4, 3, 4, 3, 4],
       [2, 2, 5, 6, 2]])

In [15]:
a.dtype, a.ndim, a.size , a.shape

(dtype('int32'), 2, 15, (3, 5))

In [16]:
b=np.array([[2.4,4.5,3,4,6],[2,6,5,4.6,8.0]])
b

array([[2.4, 4.5, 3. , 4. , 6. ],
       [2. , 6. , 5. , 4.6, 8. ]])

In [17]:
b.dtype, b.ndim, b.shape, b.size

(dtype('float64'), 2, (2, 5), 10)

In [6]:
ui=np.zeros((3,3),'d')
ui

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
ui=np.empty((4,4),'d')
ui

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.29061821e-306],
       [1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
        1.11260619e-306],
       [8.90094053e-307, 1.86919378e-306, 1.06809792e-306,
        1.37962456e-306],
       [1.69111861e-306, 1.78020169e-306, 1.37961777e-306,
        7.56599807e-307]])